const assert=require('assert');
const P=require('../ke_award/calendar_probe.js');
const row={departureDate:'20270905',emptyFare:false,fareFamilyList:['KEBONUSEY','KEBONUSPR'],fareFamilyStatus:['','']};
const wrap=r=>({boundFareCalendarList:[{departureAirport:'SEL',arrivalAirport:'CDG',fareCalendarList:r}]});
const read=d=>P.project(d,'2027-09-05','ICN','CDG');
assert.equal(read(wrap([])).state,'date-not-listed');
assert.equal(read(wrap([row])).p,true);
assert.equal(read(wrap([{...row,fareFamilyStatus:['','SOLDOUT']}])).p,false);
assert.equal(read(wrap([{...row,fareFamilyList:['KEBONUSEY'],fareFamilyStatus:['']}])).p,false);
assert.equal(read({code:503}).state,'application-error');
assert.equal(read({code:'ERT.10032'}).p,null);
assert.equal(read(wrap([{...row,departureDate:'20270904'}])).p,null);
assert.equal(read(wrap([{...row,fareFamilyStatus:[]}])).state,'schema-error');
assert.equal(P.project(wrap([row]),'2027-09-05','CDG','ICN').state,'route-mismatch');
assert.equal(read(wrap([row,row])).state,'ambiguous-date');
assert.equal(read(wrap([{departureDate:'20270905',emptyFare:true,emptyCode:'NAV'}])).p,false);
console.log('calendar parser: opening → P present → SOLDOUT/removed, errors/date/route checks passed');
// 2026-09-10 실응답: bound에는 departureDate/fareCalendarList만 존재한다.
const actual=r=>({boundFareCalendarList:[{departureDate:'20270904',fareCalendarList:r}]});
const segment=[{departureAirport:'ICN',arrivalAirport:'CDG'}];
const checked=d=>P.project(d,'2027-09-05','ICN','CDG',segment);
assert.equal(read(actual([row])).state,'route-mismatch');
assert.equal(checked(actual([])).state,'date-not-listed');
assert.equal(checked(actual([row])).p,true);
assert.equal(checked(actual([{...row,fareFamilyStatus:['','SOLDOUT']}])).p,false);
assert.equal(P.project(actual([row]),'2027-09-05','ICN','CDG',[{departureAirport:'CDG',arrivalAirport:'ICN'}]).state,'route-mismatch');
assert.equal(checked({boundFareCalendarList:[...actual([row]).boundFareCalendarList,...actual([row]).boundFareCalendarList]}).state,'route-mismatch');
assert.equal(checked({boundFareCalendarList:[{departureAirport:'CDG',arrivalAirport:'ICN',fareCalendarList:[row]}]}).state,'route-mismatch');
console.log('actual response without airports: request-bound route and P transitions passed');
